###########################
## Template profiles.yml ##
###########################

## SNOWFLAKE ##
## profile name, replace 'my_snowflake_profile' with a name of your choice  ##
my_snowflake_profile: 
  outputs:
    default:
      type: snowflake
      account: [account id]
        
      ## User/password auth, other options (Keypair/SSO) require other configs ##
      user: [username]
      password: [password]
      
      role: [user role]
      database: [database name]
      warehouse: [warehouse name]
      ## Schema is used as filter by default, you can use the 'ignore schema' 
      ## option to see cross schema lineage
      schema: [schema name]
      ## OPTIONAL - if you want to create the lineage based on queries from more 
      ## than the last 7 days or you have 10k or more queries in the history pulled during 
      ## the requested dates range, add this parameter (NOTE: account_usage requires more permissions, see note below).
      query_history_source: account_usage

## BIGQUERY ##
## profile name, replace 'my_bigquery_profile' with a name of your choice  ##
my_bigquery_profile: 
  outputs:
    default:  
      type: bigquery
      
      ## Service account auth, other options require other configs ##
      method: service-account
      keyfile: [full path to your keyfile]
      
      project: [project id]
      ## Dataset is used as filter by default, you can use the 'ignore schema' 
      ## option to see cross dataset lineage (only in the same location)
      dataset: [dataset name]
      threads: 1
      ## Location is mandatory, can be one of US or EU, or a regional location
      location: [dataset location]
      priority: interactive
