# Template profiles.yml for Snowflake

## profile name, replace 'my_profile' with a name of your choice  ##
my_profile: 

  outputs:
    default:
      type: snowflake
      account: [account id]
      
      ## User/password auth, other options (Keypair/SSO) require other configs ##
     
      user: [username]
      password: [password]
      
      role: [user role]
      database: [database name]
      warehouse: [warehouse name]
      ## Schema is used as filter by default, you can use the 'ignore schema' option to see cross schema lineage
      schema: [schema name]
      
      ## OPTIONAL - (NOTE: account_usage requires higher permissions)
      ## if you want to create the lineage based on queries from more 
      ## than the last 7 days / 10k queries add this parameter:
      
      # query_history_source: account_usage
      
