name: Bump version
on:
  workflow_dispatch:
    inputs:
      cli-version:
        type: string
        required: true
        description: New cli version
      dbt-package-version:
        type: string
        required: false
        description: Elementary package version (will use cli version if not provided)

jobs:
  validate-version:
    runs-on: ubuntu-latest
    outputs:
      validated-cli-version: ${{ steps.validate-cli-input.outputs.cli-validation }}
      default-dbt-package-version: ${{ steps.validate-cli-input.outputs.cli-validation }}
      validated-dbt-package-version: ${{ steps.validate-dbt-package-input.outputs.dbt-package-validation }}
    steps:
      - name: validate cli version input
        id: validate-cli-input
        run: echo "cli-validation=$(echo ${{ inputs.cli-version }} | sed -n '/^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$/p')" >> $GITHUB_OUTPUT
      - name: validate dbt package version
        if: ${{ inputs.dbt-package-version }}
        id: validate-dbt-package-input
        run: echo "dbt-package-validation=$(echo ${{ inputs.dbt-package-version }} | sed -n '/^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$/p')" >> $GITHUB_OUTPUT
      - name: fail on invalid input
        if: ${{ steps.validate-cli-input.outputs.cli-validation }}
        run: |
          echo "Invalid version inputs"
          exit 1

  bump-cli-version:
    needs: validate-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create release branch
        run: git checkout -b release/v${{ inputs.cli-version }}
      - name: Initial config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Bump version
        run: |
          sed -i 's/version="[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"/version="${{ inputs.cli-version }}"/' ./setup.py
          sed -i 's/version: [0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$/version: ${{ needs.validate-version.outputs.validated-dbt-package-version }}/' ./elementary/monitor/dbt_project/packages.yml
      - name: Commit changes
        run: git commit -am "release v${{ inputs.version }}"
      - name: Push code
        run: git push origin release/v${{ inputs.version }}
