name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: |
            This issue is stale because it has been open for too long with no activity.
            If you would like the issue to remain open, please remove the stale label or leave a comment.
          close-issue-message: |
            This issue was closed because it has been inactive for too long while being marked as stale.
            If you would like the issue to reopen, please leave a comment.
          stale-pr-message: |
            This pull request is stale because it has been open for too long with no activity.
            If you would like the pull request to remain open, please remove the stale label or leave a comment.
          close-pr-message: |
            This pull request was closed because it has been inactive for too long while being marked as stale.
            If you would like the pull request to reopen, please leave a comment.
