name: Release PyPI package
on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Elementary
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.5'

      - name: Install 'build' package
        run: pip install build

      - name: Build package
        run: python -m build --sdist --wheel --outdir dist .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASS }}
