name: Test all warehouse platforms
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        warehouse-type: [ snowflake, bigquery, redshift, databricks, spark ]
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: ${{ matrix.warehouse-type }}
    secrets: inherit
