name: Test main warehouse platform
on:
  pull_request:
    branches: ["master"]
    paths:
      - elementary/**
      - pyproject.toml
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: postgres
      dbt-version: 1.3.0
    secrets: inherit
