name: Test All Warehouses
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-snowflake:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: snowflake
    secrets: inherit
