name: Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Write dbt profiles
        run: echo "${{ secrets.PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Checkout Elementary
        uses: actions/checkout@v3
        with:
          path: elementary

      - name: Checkout dbt package
        uses: actions/checkout@v3
        with:
          repository: elementary-data/dbt-data-reliability
          path: dbt-data-reliability

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Elementary
        run: pip install './elementary[snowflake]'

      - name: Run E2E tests
        run: python ./dbt-data-reliability/integration_tests/run_e2e_tests.py -t snowflake

      - name: Run monitor
        run: edr monitor

      - name: Run report
        run: edr monitor report --file-path ci_report.html

      - name: Upload report artifact
      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: ci_report.html

      - name: Write Google service account
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > /tmp/google_service_account.json

      - name: Run send report
        run: edr monitor send-report --slack-token ${{ secrets.SLACK_TOKEN }} --slack-channel-name ${{ secrets.SLACK_CHANNEL_NAME }} --aws-access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --aws-secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --s3-bucket-name ${{ secrets.S3_BUCKET_NAME }} --google-service-account-path /tmp/google_service_account.json --gcs-bucket-name ${{ secrets.GCS_BUCKET_NAME }} --update-bucket-website true
