name: Test main warehouse platform
on:
  push:
    branches: [ "master" ]
    paths:
      - elementary/**
  pull_request:
    branches: [ "master" ]
    paths:
      - elementary/**
  workflow_dispatch:


jobs:
  test:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: snowflake
      dbt-version: 1.0.2
    secrets: inherit
