name: Test upgrade all warehouse platforms
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        warehouse-type: [ snowflake, bigquery, redshift, databricks, spark ]
    uses: ./.github/workflows/test-upgrade-warehouse.yml
    with:
      warehouse-type: ${{ matrix.warehouse-type }}
    secrets: inherit
