name: Test All Warehouses
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-snowflake:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test-platform
        with:
          warehouse-type: snowflake
