name: Test all warehouse platforms
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        warehouse-type: [ postgres, snowflake, bigquery, redshift, databricks ]
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: ${{ matrix.warehouse-type }}
    secrets: inherit
